version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/django
      - DEBUG=1
    depends_on:
      - pgdb


  pgdb:
    image: postgres:13-alpine
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      #- POSTGRES_USER=django
      #- POSTGRES_PASSWORD=django_QWErty!2)4
      #- POSTGRES_DB=django
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: pgdb



  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  pgdbdata: null
  static:

