# Generated by Django 4.2.1 on 2023-05-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название банка')),
                ('address', models.CharField(max_length=25, verbose_name='Месторасположение банка')),
                ('square', models.IntegerField(max_length=2, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('gender', models.CharField(max_length=7, verbose_name='Пол')),
                ('date', models.DateTimeField(max_length=10, verbose_name='Дата и время входа')),
                ('online', models.BooleanField(max_length=5, verbose_name='Онлайн')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name='Категория перевода')),
                ('price', models.IntegerField(verbose_name='Сумма перевода')),
                ('date', models.DateTimeField(max_length=19, verbose_name='Дата и время перевода')),
                ('visitorNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.visitors')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=10, verbose_name='Категория перевода')),
                ('time', models.IntegerField(max_length=1, verbose_name='Сроки перевода')),
                ('guarantee', models.BooleanField(max_length=5, verbose_name='Гарантия')),
                ('customerId', models.ManyToManyField(to='main.bank')),
            ],
            options={
                'verbose_name': 'Посредник',
                'verbose_name_plural': 'Посредники',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('gender', models.CharField(max_length=7, verbose_name='Пол')),
                ('position', models.CharField(max_length=25, verbose_name='Должность')),
                ('salary', models.IntegerField(max_length=6, verbose_name='Заработная плата')),
                ('bankId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bank')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
