# Generated by Django 4.1.7 on 2023-05-04 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=10, verbose_name='Месторасположение магазина')),
                ('square', models.IntegerField(max_length=2, verbose_name='Площадь магазина')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=10, verbose_name='Категория товара')),
                ('time', models.IntegerField(max_length=1, verbose_name='Сроки доставки')),
                ('guarantee', models.BooleanField(max_length=3, verbose_name='Гарантия на возврат')),
                ('customerId', models.ManyToManyField(to='main.shops')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('gender', models.CharField(max_length=7, verbose_name='Пол')),
                ('position', models.CharField(max_length=10, verbose_name='Должность')),
                ('salary', models.IntegerField(max_length=6, verbose_name='Заработная плата')),
                ('shopId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.shops')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
