# Generated by Django 4.2 on 2023-05-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_vendorshops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Название банка')),
                ('address', models.CharField(max_length=25, verbose_name='Месторасположение банка')),
                ('square', models.IntegerField(max_length=2, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='Intermediary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=10, verbose_name='Категория перевода')),
                ('time', models.IntegerField(max_length=1, verbose_name='Сроки перевода')),
                ('guarantee', models.BooleanField(max_length=5, verbose_name='Гарантия')),
                ('customerId', models.ManyToManyField(to='main.bank')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterModelOptions(
            name='visitors',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(max_length=19, verbose_name='Дата и время перевода'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(verbose_name='Сумма перевода'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Категория перевода'),
        ),
        migrations.DeleteModel(
            name='Vendors',
        ),
        migrations.AlterField(
            model_name='employees',
            name='shopId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.bank'),
        ),
        migrations.DeleteModel(
            name='Shops',
        ),
    ]
