# Generated by Django 4.2 on 2023-04-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(max_length=19, verbose_name='Дата и время перевода'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.IntegerField(verbose_name='Сумма перевода'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='title',
            field=models.CharField(max_length=25, verbose_name='Категория перевода'),
        ),
    ]
