# Generated by Django 4.1.7 on 2023-05-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shops_vendors_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='position',
            field=models.CharField(max_length=25, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='address',
            field=models.CharField(max_length=25, verbose_name='Месторасположение магазина'),
        ),
        migrations.AlterField(
            model_name='vendors',
            name='guarantee',
            field=models.BooleanField(max_length=5, verbose_name='Гарантия на возврат'),
        ),
    ]
