# Generated by Django 4.1.7 on 2023-05-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vendorshops'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorShops',
        ),
    ]
