# Generated by Django 4.2 on 2023-05-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_orders_options_alter_orders_date_and_more'),
        ('main', '0006_bank_intermediary_alter_orders_options_and_more'),
    ]

    operations = [
    ]
