# Generated by Django 4.2 on 2023-05-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_merge_20230521_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='shopId',
            new_name='bankId',
        ),
    ]
